### ISSUE TITLE
Detached "pop" artifacts on the map.

### ISSUE THREAD

**Issue by Torrehoradada** [projecthorus/sondehub-tracker#369]
I am sporadically discovering "pop" graphics which appear detached from any sonde track. They seem to move over time so maybe connected to a flying sonde. Clicking on the sonde (by try method) to activate the corresponding track may delete this graphic, leaving the track without any "pop"-symbol.
This actually appeares on both: The 'normal' map (www.sondehub.org) as the 'testing' (testing.v2.sondehub.org).
I cannot do screen capture movies, but here are some hardcopies (edited for data reduction):
![Bildschirmfoto vom 2024-11-20 09-09-15](https://github.com/user-attachments/assets/1219c23a-2848-454c-880d-192cf9017bda)
![grafik](https://github.com/user-attachments/assets/b8042f24-ea6e-402a-bb19-1f2c3478253e)
![grafik](https://github.com/user-attachments/assets/90ae561b-dc62-41ff-941b-17110712477b)
![grafik](https://github.com/user-attachments/assets/5ec2d9b4-b98d-4a3c-b5cd-46d9325c4a37)
![grafik](https://github.com/user-attachments/assets/06384d5a-6787-46cd-bad1-c7af0182648e)

**Comment by Torrehoradada** [comment]
![grafik](https://github.com/user-attachments/assets/7d231d2f-72c4-4e61-bf45-dcc52e2ce06c)

**Comment by TheSkorm** [comment]
Not entirely sure if this is your issue, but I pushed a fix in https://github.com/projecthorus/sondehub-tracker/pull/371 which might be the cause - can you let me know how it goes?

**Comment by Torrehoradada** [comment]
In the 'testing'-environment they are gone now.
The production-environment still have them.
